name: Codegen

on:
  repository_dispatch:
    types: [codegen]
    
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  execute_codegen:
    name: Execute codegen
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ secrets.EIN_CODEGEN_APP_ID }}
          private-key: ${{ secrets.EIN_CODEGEN_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          skip-token-revoke: true
          repositories: |
            einnsyn-codegen
            einnsyn-api-spec
            einnsyn-sdk-typescript
            einnsyn-sdk-java
            einnsyn-sdk-dotnet
            einnsyn-backend

      - name: Checkout codegen repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
  
      - name: Checkout API spec
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: felleslosninger/einnsyn-api-spec
          token: ${{ steps.app-token.outputs.token }}
          path: "einnsyn-api-spec"

      - name: Install node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'

      - name: Generate new files
        run: |
          npm install
          npm link
          npm link einnsyn-codegen
          npx tsp compile ./einnsyn-api-spec/typespec/einnsyn.tsp --emit einnsyn-codegen

      - name: Run Backend Codegen
        if: github.event.client_payload.type == '' || github.event.client_payload.type == 'backend'
        uses: ./.github/actions/codegen-backend
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr_body: ${{ github.event.client_payload.pr_body }}

      - name: Run SDK Java Codegen
        if: github.event.client_payload.type == '' || github.event.client_payload.type == 'sdk-java'
        uses: ./.github/actions/codegen-sdk-java
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr_body: ${{ github.event.client_payload.pr_body }}

      - name: Run SDK TS Codegen
        if: github.event.client_payload.type == '' || github.event.client_payload.type == 'sdk-typescript'
        uses: ./.github/actions/codegen-sdk-typescript
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr_body: ${{ github.event.client_payload.pr_body }}

      - name: Run SDK Dotnet Codegen
        if: github.event.client_payload.type == '' || github.event.client_payload.type == 'sdk-dotnet'
        uses: ./.github/actions/codegen-sdk-dotnet
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr_body: ${{ github.event.client_payload.pr_body }}
