name: Codegen

on:
  repository_dispatch:
    types: [codegen]
    
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  get_token:
    name: Fetch app installation token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.gh-api-token.outputs.token }}
    steps:
      - name: Fetch app installation token
        id: gh-api-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.EIN_CODEGEN_APP_ID }}
          private_key: ${{ secrets.EIN_CODEGEN_APP_PRIVATE_KEY }}

  execute_codegen:
    name: Execute codegen
    runs-on: ubuntu-latest
    needs: get_token

    steps:
      - name: Checkout codegen repo
        uses: actions/checkout@v4
        with:
          path: "einnsyn-codegen"
  
      - name: Checkout API spec
        uses: actions/checkout@v4
        with:
          repository: felleslosninger/einnsyn-api-spec
          token: ${{ needs.get_token.outputs.token }}
          path: "einnsyn-api-spec"

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Generate new files
        run: |
          bun install @typespec/compiler
          bun install @typespec/openapi3
          bun install ./einnsyn-codegen
          bunx tsp compile ./einnsyn-api-spec/typespec/einnsyn.tsp --emit einnsyn-codegen

  backend:
    name: Run Backend Codegen
    needs: [execute_codegen, get_token]
    if: github.event.client_payload.type == '' || github.event.client_payload.type == 'backend'
    uses: ./.github/workflows/run-codegen-backend.yml
    with:
      token: ${{ needs.get_token.outputs.token }}

  sdk_java:
    name: Run SDK Java Codegen
    needs: [execute_codegen, get_token]
    if: github.event.client_payload.type == '' || github.event.client_payload.type == 'sdk-java'
    uses: ./.github/workflows/run-codegen-sdk-java.yml
    with:
      token: ${{ needs.get_token.outputs.token }}

  sdk_ts:
    name: Run SDK TS Codegen
    needs: [execute_codegen, get_token]
    if: github.event.client_payload.type == '' || github.event.client_payload.type == 'sdk-ts'
    uses: ./.github/workflows/run-codegen-sdk-ts.yml
    with:
      token: ${{ needs.get_token.outputs.token }}
