name: Update API clients

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Fetch app installation token
        uses: tibdex/github-app-token@v1.5.2
        id: gh-api-token
        with:
          app_id: ${{ secrets.DIGDIR_PLATFORM_CI_APP_ID }}
          private_key: ${{ secrets.DIGDIR_PLATFORM_CI_APP_PRIVATE_KEY }}

      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Checkout TypeScript client repo
        uses: actions/checkout@v2
        with:
          repository: felleslosninger/ein-api-client-ts
          token: ${{ steps.gh-api-token.outputs.token }}
          path: 'ein-api-client-ts'

      - name: Generate new files
        run: |
          bun run generate

      - name: Copy files
        run: |
          cp -r out/ts-client ein-api-client-ts/

      - name: Commit and push
        run: |
          cd other-repo
          git config --local user.email "action@github.com"
          git config --local user.name "eInnsyn OpenAPI Codegen"
          git add .
          git commit -m "Update files"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.gh-api-token.outputs.token }}
          path: 'ein-api-java-client'
          commit-message: 'API version update'
          title: 'API version update'
          body: 'This PR is auto-generated to update files from ein-api-client-codegen.'
          branch: 'update-branch'
